### ISSUE TITLE
price_money field in variation not persisting through the endpoint

### ISSUE THREAD

**Issue by michaelfward** [markjen/square-connect-node-sdk#4]
I have to preface this issue by saying that my company (mid-size, >100 employees and >5 stores) had an event involving irreversible infrastructure failure almost 24 hours ago, and I am implementing a very quick and dirty replacement POS/online store for the time being. I say this because I have been going for nearly 18 hours replacing everything I can and am not entirely sure if I could spot bugs in my own code or library code at this point.

i tried to make things a bit easy for you with a jsfiddle, but it doesn't really have a lot of similarity to my code, it just shows the structure of my object that is submitted to your wrapper. http://jsfiddle.net/efjytg6r/4/

When creating an item, I noticed that the price I set is not persisted through to my square account. Here is my form (note: it is HEAVILY modified to take out all styles etc, save the base bootstrap classes for readability and brevity)

<form>
    <div class="form-group">
        <label for="item_name">Item Name</label>
        <input type="text" ng-model="itemObj.name" class="form-control" id="item_name" required />
    </div>
    <div class="input-group">
        <label for="price">Item Price</label>
        <span class="input-group-addon">$</span>
        <input type="text" ng-model="itemObj.variations.price_money.amount" class="input-control" id="price" required />
    </div>
    <div class="form-group">
        <label for="variation">Variation</label>
        <input type="text" ng-model="itemObj.variations.name" class="form-control" id="variation" required/>
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <textarea rows="4" class="form-control" ng-model="itemObj.description" id="description"></textarea>
    </div>
    <div class="form-group">
        <label for="availability">Visible Online?</label>
        <input type="checkbox" class="form-control" id="availability" ng-model="itemObj.visibility" />
    </div>
    <div class="form-group">
        <label for="del">Available online (delivery)?</label>
        <input type="checkbox" class="form-control" id="del" ng-model="itemObj.available_online" />
    </div>
    <div class="form-group">
        <label for="pick">Available for pickup?</label>
        <input type="checkbox" id="pick" class="form-control" ng-model="itemObj.available_for_pickup" />
    </div>
    <button class="btn btn-primary btn-lg" ng-click="create(itemObj)">Create</button>
</form>

here is AngularJS (modified for brevity):

controller:

```
var itemObj = {};
//set these to be the norm for now
itemObj.pricing_type = 'FIXED_PRICING';
itemObj.price_money = {
    currency_code: 'USD'
};

//set up the model
$scope.itemObj = {};
$scope.itemObj.variations = itemObj;
function verify_and_return(str){
 var reg = /^\d*\.{0,1}\d{0,2}$/;
 var test = reg.test(str);
 if (test == false){
    //didnt work
 } else {
    return parseFloat(str);
 }
}
```

   $scope.create = function(item){
     item.variations.price_money.amount = verify_and_return(item.variations.price_money.amount);
     ItemService.create(item)
       .then(handleRes, handleRes);
   }

service:
    this.create = function(item){
        return $http.post('/square/item', {
            item: item
        });
    }

and here is my route handler on my express server (again, heavily modified for brevity):
  squareRouter.post('/item', function(req, res){
    var item = req.body.item;
    square.api('/me/items', 'POST', item, function(err, resp){
        data_handler(err, resp, res);
    });
  });

**Comment by tdeck** [comment]
I believe the problem you're having is that item.variations is expected to be an array. It looks like we're not doing a good job of error messaging in this case.

**Comment by michaelfward** [comment]
Thank you for the reply. I actually discovered that the issue was me not thoroughly reading the square docs and handling the object a bit incorrectly (one of the things I was doing wrong was assuming that square took my amount obj, for instance 2.13, and converted it to cents themselves). All of the issues are resolved and were on my side, not your library. Thank you!
